In [1]:
import pandas as pd

# Part A — Load & Explore

## 1: Load pandasmart_sales.csv into a DataFrame

In [84]:
df = pd.read_csv("pandasmart_sales.csv")
df

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj
1,1002,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj
3,1004,NaN,Bangalore,Furniture,3,12000,2024-02-14,Amit
4,1005,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj
6,1007,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya
7,1008,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit
8,1009,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj

## 2: Print the first 5 rows, last 3 rows, and the shape

In [10]:
first_5 = df.head()
first_5

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj
1,1002,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj
3,1004,NaN,Bangalore,Furniture,3,12000,2024-02-14,Amit
4,1005,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya

In [11]:
last_5 = df.tail()
last_5

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep
6,1007,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya
7,1008,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit
8,1009,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj

## 3: Print column names, data types, and non-null counts using .info()

In [15]:
columns = df.info()
columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       11 non-null     int64
 1   CustomerName  10 non-null     object
 2   City          11 non-null     object
 3   Category      10 non-null     object
 4   Quantity      11 non-null     int64
 5   UnitPrice     11 non-null     int64
 6   OrderDate     11 non-null     object
 7   SalesRep      11 non-null     object
dtypes: int64(3), object(5)
memory usage: 836.0+ bytes

## 4: Print summary statistics using

In [17]:
describe = df.describe()
describe

           OrderID   Quantity     UnitPrice
count    11.000000  11.000000     11.000000
mean   1006.000000   2.727273  11190.909091
std       3.316625   1.420627   8613.530582
min    1001.000000   1.000000    800.000000
25%    1003.500000   2.000000   3250.000000
50%    1006.000000   2.000000  12000.000000
75%    1008.500000   3.500000  16500.000000
max    1011.000000   5.000000  25000.000000

## 5: Print how many missing values exist in each column

In [22]:
missing = df.isnull().sum()
missing

OrderID         0
CustomerName    1
City            0
Category        1
Quantity        0
UnitPrice       0
OrderDate       0
SalesRep        0
dtype: int64

# Part B — Data Cleaning

## 1: Drop rows where CustomerName is missing

In [25]:
dropped_df = df.dropna()
dropped_df

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj
1,1002,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj
4,1005,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj
6,1007,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya
7,1008,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj

## 2: Fill missing Category values with the string "Unknown"

In [44]:
filling_na = df['Category'].fillna("Unknown")
df

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep,TotalSale
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000
1,1002,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj,25000
3,1004,NaN,Bangalore,Furniture,3,12000,2024-02-14,Amit,36000
4,1005,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya,3000
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj,32000
6,1007,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000
7,1008,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit,22000
8,1009,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj,10000
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya,54000
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000

## 3: Remove duplicate rows — identify them first using .duplicated(), then drop them

In [27]:
duplicated_rows = df.duplicated()
duplicated_rows

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [30]:
drop_duplicated_rows = df.drop_duplicates()
drop_duplicated_rows

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj
1,1002,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj
3,1004,NaN,Bangalore,Furniture,3,12000,2024-02-14,Amit
4,1005,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj
6,1007,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya
7,1008,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit
8,1009,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj

## 4: Convert OrderDate to datetime using pd.to_datetime()

In [37]:
new_datetime = pd.to_datetime(df['OrderDate'])
df['OrderDate'] = new_datetime
df

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj
1,1002,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj
3,1004,NaN,Bangalore,Furniture,3,12000,2024-02-14,Amit
4,1005,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj
6,1007,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya
7,1008,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit
8,1009,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj

## 5: Add a new column TotalSale = Quantity × UnitPrice

In [40]:
df['TotalSale'] = df['Quantity'] * df['UnitPrice']
df

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep,TotalSale
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000
1,1002,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj,25000
3,1004,NaN,Bangalore,Furniture,3,12000,2024-02-14,Amit,36000
4,1005,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya,3000
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj,32000
6,1007,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000
7,1008,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit,22000
8,1009,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj,10000
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya,54000
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000

## 6: Standardize the City column to title case using .str.title()

In [42]:
df['City'].str.title()
df

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep,TotalSale
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000
1,1002,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj,25000
3,1004,NaN,Bangalore,Furniture,3,12000,2024-02-14,Amit,36000
4,1005,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya,3000
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj,32000
6,1007,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000
7,1008,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit,22000
8,1009,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj,10000
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya,54000
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000

# Part C — Selection & Filtering
Using the cleaned DataFrame:

## 1: Select only the CustomerName, Category, and TotalSale columns

In [48]:
df[["CustomerName", "Category", "TotalSale"]]

   CustomerName     Category  TotalSale
0         Alice  Electronics      30000
1           Bob     Clothing       4000
2       Charlie  Electronics      25000
3           NaN    Furniture      36000
4           Eve     Clothing       3000
5         Frank  Electronics      32000
6           Bob     Clothing       4000
7         Grace    Furniture      22000
8         Heidi          NaN      10000
9          Ivan  Electronics      54000
10        Alice  Electronics      30000

## 2: Use .loc[] to get rows where City is "Delhi"

In [51]:
df.loc[df['City'] == 'Delhi']

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep,TotalSale
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj,25000
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj,32000
8,1009,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj,10000
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000

## 3: Use .iloc[] to get the first 3 rows and first 4 columns

In [52]:
df.iloc[0:3, 0:4]

   OrderID CustomerName    City     Category
0     1001        Alice   Delhi  Electronics
1     1002          Bob  Mumbai     Clothing
2     1003      Charlie   Delhi  Electronics

## 4: Use .query() to find all orders where TotalSale > 30000 and City == 'Mumbai'

In [53]:
df.query("TotalSale > 30000 and City == 'Mumbai'")

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep,TotalSale
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya,54000

## 5: Find all Electronics orders placed by SalesRep "Raj" using boolean masking

In [55]:
df.query("Category == 'Electronics' and SalesRep == 'Raj'")

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep,TotalSale
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj,25000
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj,32000
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000

## 6: Use .at[] to get the CustomerName of the order at index 0

In [57]:
df.at[0, "CustomerName"]

'Alice'

# Part D — Sorting & Transformation

## 1: Sort the DataFrame by TotalSale descending

In [58]:
df.sort_values("TotalSale", ascending=False)

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep,TotalSale
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya,54000
3,1004,NaN,Bangalore,Furniture,3,12000,2024-02-14,Amit,36000
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj,32000
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj,25000
7,1008,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit,22000
8,1009,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj,10000
1,1002,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000
6,1007,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000
4,1005,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya,3000

In [60]:
df.sort_values(["City", "TotalSale"], ascending=[True, False])

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep,TotalSale
3,1004,NaN,Bangalore,Furniture,3,12000,2024-02-14,Amit,36000
7,1008,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit,22000
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj,32000
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj,25000
8,1009,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj,10000
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya,54000
1,1002,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000
6,1007,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000
4,1005,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya,3000

## 3: Add a column SaleCategory using .apply() with this logic:

- TotalSale >= 50000 → "High"
- TotalSale >= 20000 → "Medium"
- Anything below → "Low"

In [62]:
def logic(sale):
    if sale >= 50000:
        return "High"
    elif sale >= 20000:
        return "Medium"
    else:
        return "Low"

df['SaleCategory'] = df['TotalSale'].apply(logic)
df

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,SalesRep,TotalSale,SaleCategory
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000,Medium
1,1002,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000,Low
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj,25000,Medium
3,1004,NaN,Bangalore,Furniture,3,12000,2024-02-14,Amit,36000,Medium
4,1005,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya,3000,Low
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj,32000,Medium
6,1007,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000,Low
7,1008,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit,22000,Medium
8,1009,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj,10000,Low
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya,54000,High
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000,Medium

## 4: Rename the column SalesRep to Representative

In [65]:
df.rename(columns={'SalesRep': 'Representative'}, inplace=True)
df

,OrderID,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,Representative,TotalSale,SaleCategory
0,1001,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000,Medium
1,1002,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000,Low
2,1003,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj,25000,Medium
3,1004,NaN,Bangalore,Furniture,3,12000,2024-02-14,Amit,36000,Medium
4,1005,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya,3000,Low
5,1006,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj,32000,Medium
6,1007,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya,4000,Low
7,1008,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit,22000,Medium
8,1009,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj,10000,Low
9,1010,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya,54000,High
10,1011,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj,30000,Medium

## 5: Reorder columns so TotalSale and SaleCategory appear right after OrderID

In [68]:
df.columns

Index(['OrderID', 'CustomerName', 'City', 'Category', 'Quantity', 'UnitPrice',
       'OrderDate', 'Representative', 'TotalSale', 'SaleCategory'],
      dtype='object')

In [69]:
df[['OrderID', 'TotalSale', 'SaleCategory', 'CustomerName', 'City', 'Category', 'Quantity', 'UnitPrice', 'OrderDate', 'Representative']]

,OrderID,TotalSale,SaleCategory,CustomerName,City,Category,Quantity,UnitPrice,OrderDate,Representative
0,1001,30000,Medium,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj
1,1002,4000,Low,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya
2,1003,25000,Medium,Charlie,Delhi,Electronics,1,25000,2024-02-10,Raj
3,1004,36000,Medium,NaN,Bangalore,Furniture,3,12000,2024-02-14,Amit
4,1005,3000,Low,Eve,Mumbai,Clothing,2,1500,2024-03-05,Priya
5,1006,32000,Medium,Frank,Delhi,Electronics,4,8000,2024-03-18,Raj
6,1007,4000,Low,Bob,Mumbai,Clothing,5,800,2024-01-20,Priya
7,1008,22000,Medium,Grace,Bangalore,Furniture,1,22000,2024-04-02,Amit
8,1009,10000,Low,Heidi,Delhi,NaN,2,5000,2024-04-15,Raj
9,1010,54000,High,Ivan,Mumbai,Electronics,3,18000,2024-05-01,Priya
10,1011,30000,Medium,Alice,Delhi,Electronics,2,15000,2024-01-15,Raj

# Part E — Melt & Pivot

You have this wide-format summary table — create it as a new DataFrame:

In [71]:
summary = pd.DataFrame({
    "SalesRep": ["Raj", "Priya", "Amit"],
    "Q1_Sales": [48000, 12500, 36000],
    "Q2_Sales": [32000, 54000, 22000],
    "Q3_Sales": [61000, 29000, 47000]
})

## 1: Use melt() to convert it to long format with columns SalesRep, Quarter, Sales

In [76]:
melted = summary.melt(id_vars='SalesRep', var_name="Quarter", value_name="Sales")
melted

  SalesRep   Quarter  Sales
0      Raj  Q1_Sales  48000
1    Priya  Q1_Sales  12500
2     Amit  Q1_Sales  36000
3      Raj  Q2_Sales  32000
4    Priya  Q2_Sales  54000
5     Amit  Q2_Sales  22000
6      Raj  Q3_Sales  61000
7    Priya  Q3_Sales  29000
8     Amit  Q3_Sales  47000

## 2: Use pivot() to convert the melted DataFrame back to wide format

In [81]:
wide = melted.pivot(index="SalesRep", columns="Quarter", values="Sales")
wide

Quarter   Q1_Sales  Q2_Sales  Q3_Sales
SalesRep
Amit         36000     22000     47000
Priya        12500     54000     29000
Raj          48000     32000     61000

## 3: Confirm both DataFrames have the same values — what do you notice about the column order?

In [83]:
'''
    the melted dataframe contains more more rows and repeated data,
    and pivot dataframe has only 3 rows but contains the same amount of input as melt dataframe
'''

'\n    the melted dataframe contains more more rows and repeated data,\n    and pivot dataframe has only 3 rows but contains the same amount of input as melt dataframe\n'

# Part F — Read & Write

## 1: Save the cleaned DataFrame to cleaned_pandasmart.csv without the index

In [89]:
copied_csv = df.copy()
dropped_na = copied_csv.dropna()
dropped_na.to_csv("cleaned_pandasmart.csv", index=False)

## 2: Save the melted summary to quarterly_summary.json

In [92]:
melted.to_json("quarterly_summary.json", indent=4)

## 3: Save both the cleaned DataFrame and the pivot table to separate sheets in one Excel file called pandasmart_report.xlsx — sheets named "Sales" and "Quarterly"

In [93]:
with pd.ExcelWriter("pandasmart_report.xlsx") as writer:
    dropped_na.to_excel(writer, sheet_name="Sales", index=False)
    wide.to_excel(writer, sheet_name="Quaterly", index=False)